config/routes.rb
BrewApp::Application.routes.draw do
  get "users/show"
  devise_for :users
  root "brews#index"
  resources :brews
  get 'about' => 'brews#about'
end

app/models/brew.rb
class Brew < ActiveRecord::Base
	belongs_to :user
	has_many :fermentables
	has_many :extras
	has_many :hops
	has_many :yeasts
	accepts_nested_attributes_for :hops, allow_destroy: true
	accepts_nested_attributes_for :fermentables, allow_destroy: true
	accepts_nested_attributes_for :extras, allow_destroy: true
	accepts_nested_attributes_for :yeasts, allow_destroy: true
	
	validates :name, :story, :walkthrough, presence: true

end

app/models/extra.rb
class Extra < ActiveRecord::Base
  belongs_to :brew
end

app/models/fermentable.rb
class Fermentable < ActiveRecord::Base
  belongs_to :brew
  validates :brew_id, presence: true
end

app/models/hop.rb
class Hop < ActiveRecord::Base
  belongs_to :brew
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         validates :email, uniqueness: true

   has_many :brews
end

app/models/yeast.rb
class Yeast < ActiveRecord::Base
  belongs_to :brew
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/brews_controller.rb
class BrewsController < ApplicationController
  def index
  	@brews = Brew.order("created_at desc")
  end

  def new
  	@brew = Brew.new
  	@brew.hops.build
    @brew.fermentables.build
    @brew.yeasts.build
    @brew.extras.build
  end

  def show
  	@brew = Brew.find params[:id]
  end

  def edit
    @brew = Brew.find params[:id]
  end

  def create
  	@brew = Brew.new(brew_params)
    @brew.user = User.find(current_user.id)
   	if @brew.save
   		redirect_to @brew
   	else
   		render 'new'
   	end
  end

 def update
  @brew = Brew.find params[:id]
  @brew.update brew_params
  redirect_to @brew
 end

def destroy
    @brew = Brew.find params[:id]
    @brew.destroy
    redirect_to root_path
end

private 
  def brew_params
  	params.require('brew').permit(:name, :story, :walkthrough, hops_attributes: [:name, :id, :brew_id], 
      extras_attributes: [:name, :id, :brew_id], fermentables_attributes: [:name, :id, :brew_id], 
      yeasts_attributes: [:name, :id, :brew_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/brews_helper.rb
module BrewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/brews/_brews.html.erb
<% @brews.each do |brew| %>
	
		<div class = "box">
					<h1><%= link_to (brew.name), brew %></h1>
			  	<p><%= truncate(brew.story, length: 300) %></p>	
		</div>
<% end %>

app/views/brews/_extras.html.erb
	<p>
		<%=  f.label :name, "Extras" %>
		<%=  f.text_field :name %>
	

	</p>

app/views/brews/_fermentables.html.erb
<p>
		<%=  f.label :name, "Fermentables" %>
		<%=  f.text_field :name %>
		
</p>

app/views/brews/_form.html.erb
<div>
<%= nested_form_for @brew do |f| %>
	<div class="span6">
		<p><%= f.label :name, "Beer Name" %> <br />
			<%= f.text_field :name %><br />
			<%= f.label :story, "Brew Story" %><br />
			<%= f.text_area :story %><br />
			<%= f.label :walkthrough, "Recipe Walkthrough" %><br />
			<%= f.text_area :walkthrough %><br />
		</p>
	</div>

			<div class= "span4">
				<p>Fermentables</p>	
						<%= f.fields_for :fermentables do |fermentables| %>		
						<%= fermentables.text_field :name %>
						<%= fermentables.link_to_remove "Remove -" %>
					<% end %>
				<p><%= f.link_to_add "Add +", :fermentables %></p>
				<p>Hops</p>	
					<%= f.fields_for :hops do |hops| %>
						<%= hops.text_field :name%>
						<%= hops.link_to_remove "Remove -" %>
					<% end %>
				<p><%= f.link_to_add "Add +", :hops %></p>


					<%= f.fields_for :yeasts do |yeasts| %>
						<%= render 'yeasts', f: yeasts %>
					<% end %>
				

					<%= f.fields_for :extras do |extras| %>
						<%= render 'extras', f: extras %>
					<% end %>
			</div>
	<div class="span1">
		<p> <%= f.submit %> </p>
		<% end %>
	</div>
</div>

app/views/brews/_hops.html.erb
<p>
		<%=  f.label :name, "Hops" %>
		<%=  f.text_field :name %>
	

</p>

app/views/brews/_yeasts.html.erb
<p>
		<%=  f.label :name, "Yeast" %>
		<%=  f.text_field :name %>


</p>

app/views/brews/about.html.erb
sup son

<%= link_to "My brews", users_show_path %>

app/views/brews/edit.html.erb
<%= render 'form' %>

app/views/brews/index.html.erb
<div id = "brews">
	<%= render 'brews' %>
</div>

app/views/brews/new.html.erb
<% if @brew.errors.any? %>
	<h2>There were errors saving your brew</h2>
	<ul>
  	<% @brew.errors.full_messages.each do |msg| %>
  	<li><%= msg %></li>
  	<% end %>
  <ul>
 <% end %>

<%= render 'form' %>

app/views/brews/show.html.erb
<div class = "span6">
		<h1><%= @brew.name %></h1>
		<h4> The Story </h4>
  	<p><%= @brew.story %></p>
  	<h4>Walk through the brew</h4>
   	<p><%= @brew.walkthrough %></p>		
 </div>

<div class="span4 pull-right">	
	<h3>Ingredients</h3>
		<% @brew.fermentables.each do |fermentable| %>
		  	<%=fermentable.name.capitalize %> |
		<% end %>

		<% @brew.hops.each do |hop| %>
		  	<%=hop.name.capitalize %> |
		<% end %>

		<% @brew.yeasts.each do |yeasts| %>
		  	<%=yeasts.name.capitalize %> |
		<% end %>

		<% @brew.extras.each do |extras| %>
		  	<%=extras.name.capitalize %></p>
		<% end %>
		<div>
   		<% if @brew.user == current_user %>
   			<p>	
   				<%= (link_to "Edit", edit_brew_path, :class => 'btn') %> |
   				<%= (link_to 'Delete Beer', @brew, :class => 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?'}) %>
   			</p>
   		<%end %>
		</div>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
     
      <%= link_to "BrewStories",root_path, class: "brand" %>
 
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
          <ul class="nav">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "About", about_path %></li>
         
            <% if user_signed_in? %>
            <li><%= link_to "Add Brew +", new_brew_path %></li>
          </ul>
          <ul class= "nav pull-right">
              <li><%= link_to " #{current_user.email}", users_show_path %></li>
              <li><%= link_to "Edit Account", edit_user_registration_path %></li>
              <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
          <% else %>
            <li><%= link_to "Login", new_user_session_path %></li>
            <li> <%= link_to "Sign Up", new_user_registration_path %> </li>
          <% end %>
        </ul>
        <!-- .nav, .navbar-search, .navbar-form, etc -->
      </div>
 
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BrewApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag :defaults, "nested_form" %>
  <%= csrf_meta_tags %>
</head>
<body>
				<%= render 'layouts/navbar' %>

				<!-- <p class="notice"><%= notice %></p>
       	<p class="alert"><%= alert %></p>-->


<div class="container-fluid">
  <div class="row-fluid">
    <div class="span2">
      <h1>How_to</h1>
      <p>
      Get a magazine that you do not want anymore. Cut about four or five pages out. We'll use them in the next step. Look for bright colors to get your attention but if you do not have that, then it is fine without.
     </p>
    </div>
    <div class="span10">
      <!--Body content-->
      <%= yield %>
    </div>
  </div>
</div>



</body>
</html>

app/views/users/show.html.erb
<h1>Users#show</h1>
	<% @user.brews.each do |brew| %>
		<fieldset>

			<h1><%= brew.name %></h1>
	  	<p><%= brew.story %></p>
				<%= link_to "Show", brew %>
			
		</fieldset>
<% end %>